ALTER TABLE public.exams
  ADD COLUMN IF NOT EXISTS title TEXT,
  ADD COLUMN IF NOT EXISTS exam_type TEXT NOT NULL DEFAULT 'final',
  ADD COLUMN IF NOT EXISTS end_time TIME,
  ADD COLUMN IF NOT EXISTS faculty TEXT,
  ADD COLUMN IF NOT EXISTS max_marks NUMERIC,
  ADD COLUMN IF NOT EXISTS passing_marks NUMERIC,
  ADD COLUMN IF NOT EXISTS expected_marks NUMERIC,
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'upcoming',
  ADD COLUMN IF NOT EXISTS chapters_completed INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chapters_total INTEGER NOT NULL DEFAULT 0;